# PyTorch Basics

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.13.1+cpu'

In [3]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [4]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
print()
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32) <class 'torch.Tensor'>


In [5]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [6]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
torch.rand(3, 3, 3)

tensor([[[0.6242, 0.8940, 0.7576],
         [0.4224, 0.0610, 0.9276],
         [0.9857, 0.0397, 0.9890]],

        [[0.3597, 0.5118, 0.0915],
         [0.4916, 0.4899, 0.1413],
         [0.3552, 0.6969, 0.1140]],

        [[0.9805, 0.4161, 0.3433],
         [0.7958, 0.1340, 0.7243],
         [0.9028, 0.2870, 0.1328]]])

In [8]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)
print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [9]:
zero_tensor[0]

tensor([0., 0., 0.])

In [10]:
ones_like_zeros[:, 0]

tensor([1., 1., 1.])

In [11]:
x = ones_like_zeros.detach()
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
x[:, 0] * 5

tensor([5., 5., 5.])

In [13]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(0.7826)

In [14]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[0.9710, 1.3631, 1.1902, 1.7926, 1.3307],
        [0.5110, 1.0120, 0.7704, 1.0745, 0.7292],
        [0.8286, 1.0857, 0.9273, 1.3828, 1.0320],
        [0.9134, 0.9089, 0.8239, 1.3444, 1.1411],
        [0.8206, 1.4634, 1.0104, 1.6492, 1.4222]])